services:
  asql:
    container_name: asql
    build: .
    # command: ["/usr/local/mysql/bin/mysqld_safe", "--user=mysql", "&", ";", "/usr/local/mysql/bin/mysql", "-u root", "--skip-password"]
    command: ["sh", "-c", "sleep 100h"]